### ISSUE TITLE
More unit-tests and types for generated types

### ISSUE THREAD

**Issue by ingvagabund** [gofed/symbols-extractor#1]
We need more definitions of various types (possibly with multiple level of recursion) to test generated types. Anything from structs in struct to interface with functions, some of them with function types, etc.

This will be needed very soon so are highly confident the generated code is usable and error prune for upcoming modifications (and extensions).

In case cases it make sense to generate the tests. E.g.

```yaml
symboltable:
- "var MyInt int"
- "type MyStruct struct {...}"
- "func MyFunc(MyInt) int"
- "func MyFuncStr(MyInt) string"
targets:
- target: "parseBinaryExpr"
  tests:
  - code: "MyInt(2) + 3"
    expected: "MyInt"
  - code: "MyFunc(MyInt(3)) + MyFunc(MyInt(3))"
    expected: "int"
  - code: "MyInt(MyFunc(MyInt(3))) + MyFunc(MyInt(3))"
    expected: "MyInt"
- target: "parseCallExpr"
  tests:
  - code: "MyFunc(MyInt(3))"
    expected: "int"
  - code: "MyFuncStr(MyInt(2))"
    expected: "string"
```
